version: '3'
services:
  frontend:
    build:
      context: .
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - frontend
